cacheFolder: ./.yarn/cache

changesetBaseRefs:
  - master
  - origin/master
  - upstream/master
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.test.{js,ts}"

cloneConcurrency: 8

compressionLevel: mixed

enableColors: true

enableGlobalCache: false

enableHyperlinks: true

enableInlineBuilds: false

enableMessageNames: true

enableProgressBars: true

enableScripts: true

enableTimers: true

lockfileFilename: yarn.lock

networkConcurrency: 45

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
